/**********************************************************************************/
/*  Problem: d760 "10330 - Power Transmission" from 10330 - Power Transmission    */
/*  Language: CPP (1564 Bytes)                                                    */
/*  Result: AC(4ms, 440KB) judge by this@ZeroJudge                                */
/*  Author: pig840502 at 2011-12-22 21:08:52                                      */
/**********************************************************************************/
#include<stdio.h>
#include<string.h>
#include<queue>
#define MAX 103
#define MIN(x,y) ( (x) >= (y) ? (y) : (x) )
#define INF 2e9
int F[MAX][MAX],C[MAX][MAX],R[MAX][MAX]; // 0 Source , 1 Sink
int Vertex_R[MAX];
bool visit[MAX];
int flow[MAX];
int path[MAX];
int n,m;
int BFS(int s,int t){
	memset(visit,false,sizeof(visit));
	std::queue<int> Q;
	visit[s]=true;
	flow[s]=INF;
	path[s]=s;
	Q.push(s);
	while(!Q.empty()){
		int i=Q.front(); Q.pop();
		for(int j=0;j<=n+1;j++)
			if(Vertex_R[j]>0&&R[i][j]>0&&!visit[j]){
				visit[j]=true;
				Q.push(j);
				flow[j]=MIN(flow[i],R[i][j]);
				flow[j]=MIN(Vertex_R[j],flow[j]);
				path[j]=i;
				if(j==t)
					return flow[t];
			}
	}
	return 0;
}
int Edmonds_Karp(int s,int t){
	memset(F,0,sizeof(F));
	memcpy(R,C,sizeof(C));
	int sum_f,f;
	for(sum_f=0;f=BFS(s,t);sum_f+=f)
		for(int i=path[t],j=t;i!=j;j=i,i=path[i]){
			F[i][j]+=f;
			F[j][i]-=F[i][j];
			R[i][j]=C[i][j]-F[i][j];
			R[j][i]=C[j][i]-F[j][i];
			Vertex_R[i]-=f;
		}
	return sum_f;
}
void initial(){
	memset(C,0,sizeof(C));
}
int main(){
	while(scanf("%d",&n)==1){
		int s,t,k;
		initial();
		for(int i=1;i<=n;i++)
			scanf("%d",&Vertex_R[i]);
		Vertex_R[n+1]=INF;
		scanf("%d",&m);
		for(int i=0;i<m;i++){
			scanf("%d%d%d",&s,&t,&k);
			C[s][t]=k;
		}		
		scanf("%d%d",&s,&t);
		for(int i=0;i<s;i++){
			scanf("%d",&k);
			C[0][k]=INF;
		}
		for(int i=0;i<t;i++){
			scanf("%d",&k);
			C[k][n+1]=INF;
		}
		int ans=Edmonds_Karp(0,n+1);
		printf("%d\n",ans);
	}
	return 0;
}
/*

DESA is taking a new project to transfer power. Power is generated by the newly established plant in Barisal. The main aim of this project is to transfer Power in Dhaka. As Dhaka is a megacity with almost 10 million people DESA wants to transfer maximum amount of power through the network. But as always occurs in case of power transmission it is tough to resist loss. So they want to use some regulators whose main aim are to divert power through several outlets without any loss. 

Each such regulator has different capacity. It means if a regulator gets 100 unit power and it's capacity is 80 unit then remaining 20 unit power will be lost. Moreover each unidirectional link( Connectors among regulators) has a certain capacity. A link with capacity 20 unit cannot transfer power more than 20 unit. Each regulator can distribute the input power among the outgoing links so that no link capacity is overflown. DESA wants to know the maximum amount of power which can be transmitted throughout the network so that no power loss occurs. That is the job you have to do. 

( Do not try to mix the above description with the real power transmission.) 

The Input
 
The input will start with a postive integer N ( 1<=N<=100 ) indicates the number of regulators. The next few lines contain N positive integers indicating the capacity of each regulator from 1 to N. The next line contains another positive integer M which is the number of links available among the regulators. Following M lines contain 3 positive integers ( i j C) each. 'i' and 'j' is the regulator index ( 1<=i,j<=N) and C is the capacity of the link. Power can transfer from i'th regulator to j'th regulator. The next line contains another two positive integers B and D. B is the number of regulators which are the entry point of the network. Power generated in Barisal must enter in the network through these entry points. Simmilarly D is the number of regulators connected to Dhaka. These links are special and have infinite capacity. Next line will contain B+D integers each of which is an index of regulator. The first B integers are the index of regulators connected with Barisal. Regulators connected with Barisal are not connected with Dhaka.

 Input is terminated by EOF. 

The Output
 
For each test case show the maximum amount of power which can be transferred to Dhaka from Barisal. Use a seperate line for each test case.
 
Sample Input
 
4
10 20 30 40
6
1 2 5
1 3 10
1 4 13
2 3 5
2 4 7
3 4 20
3 1
1 2 3 4
2
50 100
1
1 2 100
1 1
1 2
 
Sample Output

37
50

--------------------------------------------------------------------------------
Md. Kamruzzaman

*/